# fly.toml app configuration file generated for lvl-6repya on 2025-07-26T21:30:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lvl-6repya'
primary_region = 'lax'

[build]
  [build.args]
    GO_VERSION = '1.24.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
