// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package lvl

type Habit struct {
	ID    int64
	Name  string
	Level int64
	Exp   int64
}

type Habitlog struct {
	ID      int64
	HabitID int64
	LogDate int64
}
